import google.generativeai as genai
from typing import Dict, Any
import os
from datetime import datetime

class ArchitectAI:
    """
    Architect AI Persona - Generates system design and architecture
    from requirements documentation.
    """
    
    def __init__(self):
        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            raise ValueError("GEMINI_API_KEY environment variable not set")
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('models/gemini-2.5-flash')
        self.fallback_model = genai.GenerativeModel('models/gemini-1.5-flash')  # Lighter fallback
        self.persona_version = "v1.0.0"
        
    def design_architecture(self, requirements: str, context: Dict[str, Any] = None) -> str:
        """
        Generate SYSTEM_DESIGN.md from requirements
        
        Args:
            requirements: FEATURE_REQUIREMENTS.md content
            context: Project architecture context
        
        Returns:
            Formatted SYSTEM_DESIGN.md content
        """
        
        prompt = f"""
You are an Architect AI persona (v{self.persona_version}) - an expert Software Architect and System Designer.

Your task is to analyze the requirements document and generate a comprehensive SYSTEM_DESIGN.md 
file following this structure:

## Required Sections:

1. **Executive Summary**
   - Feature name and architecture type
   - Design pattern to follow
   - High-level approach

2. **Requirements Analysis Summary**
   - Key requirements identified
   - Technical scope
   - Complexity assessment

3. **High-Level Design (HLD)**
   - Component architecture overview
   - Data flow architecture
   - Integration points
   - Use Mermaid diagrams for visualization

4. **Low-Level Design (LLD)**
   - Component structure details
   - File/module organization
   - API contracts
   - Data models
   - Code examples (TypeScript/Python)

5. **Technical Implementation Strategy**
   - Phase 1: Core component development
   - Phase 2: Integration
   - Phase 3: Testing & validation

6. **Risk Assessment & Mitigation**
   - Technical risks
   - Mitigation strategies

## Context:
{f"Architecture Context: {context}" if context else "No additional context provided"}

## Requirements Document (Summary):
{requirements[:1000]}...

Generate a detailed SYSTEM_DESIGN.md with:
- Mermaid diagrams for architecture visualization
- Specific code examples
- Clear component boundaries
- Implementation-ready specifications

Keep the response focused and concise. Prioritize clarity over length.
"""

        # Configure generation settings
        generation_config = {
            'temperature': 0.7,
            'top_p': 0.95,
            'top_k': 40,
            'max_output_tokens': 4096,
        }

        # Try primary model, fallback to lighter model if overloaded
        try:
            response = self.model.generate_content(
                prompt,
                generation_config=generation_config
            )
        except Exception as e:
            error_str = str(e).lower()
            if "503" in str(e) or "overloaded" in error_str or "unavailable" in error_str:
                print("   ⚠️  Primary model overloaded, trying fallback model (gemini-1.5-flash)...")
                response = self.fallback_model.generate_content(
                    prompt,
                    generation_config=generation_config
                )
            else:
                raise

        # Handle multi-part responses
        try:
            output = response.text.strip()
        except ValueError:
            # Response has multiple parts, concatenate them
            output = ""
            for candidate in response.candidates:
                for part in candidate.content.parts:
                    if hasattr(part, 'text'):
                        output += part.text
            output = output.strip()

        # Strip markdown code fences if present
        if output.startswith('```markdown'):
            output = output[len('```markdown'):].strip()
        if output.startswith('```'):
            output = output[3:].strip()
        if output.endswith('```'):
            output = output[:-3].strip()

        # Add AI generation footprint
        output += f"\n\n---\n\n## AI Generation Footprint\n\n"
        output += f"**Generated By**: Architect AI\n\n"
        output += f"**Framework Version**: {self.persona_version}\n\n"
        output += f"**Generation Date**: {datetime.utcnow().isoformat()} UTC\n\n"
        output += f"**Architecture Design Status**: ✅ COMPLETE\n\n"
        output += f"---\n\n"
        output += f"Co-authored by Architect AI using Persona-Driven AI Framework {self.persona_version}\n"
        
        return output
    
    def validate_output(self, output: str) -> Dict[str, Any]:
        """Validate architecture design quality"""
        output_lower = output.lower()

        validation = {
            "has_hld": ("high-level design" in output_lower or "hld" in output_lower or
                       "architecture" in output_lower or "system design" in output_lower),
            "has_lld": ("low-level design" in output_lower or "lld" in output_lower or
                       "component" in output_lower or "implementation" in output_lower),
            "has_diagrams": "```mermaid" in output or "diagram" in output_lower,
            "has_code_examples": "```" in output,
            "has_implementation_strategy": ("implementation" in output_lower or
                                           "strategy" in output_lower or
                                           "approach" in output_lower),
            "word_count": len(output.split()),
        }
        validation["is_valid"] = all([
            validation["has_hld"] or validation["has_lld"],  # At least one design section
            validation["word_count"] > 300  # Reduced from 800 to be more lenient
        ])
        return validation

